meta_product_name: "Shareflix"
meta_title: "Welcome to Shareflix!"
meta_description: "Open your account to the community and get access to all member's accounts."
meta_image: "img-shareflix.png" # should exist in `app/assets/images/`
